# Generated by Django 5.2.17 on 2026-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animesouce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.URLField(blank=True, max_length=2083, verbose_name='Картинка (ссылка)'),
        ),
    ]
